### ISSUE TITLE
Async items

### ISSUE THREAD

**Issue by michalpokojski** [dylangarcia/react-use-pagination#1]
Super useful component :) Great work!

I've found one bug. It doesn't work with async items.

simple fix:
```JavaScript
useEffect(() => {
  dispatch({ type: 'reset', initialState: props })
}, [props.items])
```

and everything works fine :)

I also tried on my side to trigger almost the same thing by using `pagination.onResetPage()` but `useCallback` from react memoize initial props so `useEffect` has come in handy 👍

**Comment by dylangarcia** [comment]
@michalpokojski so sorry I didn't see this! Glad you like it.

Can you provide a minimal repro for your issue? I think if I just add `props` to the dependency array of useCallback it should fix it!

**Comment by michalpokojski** [comment]
Actually, it's already there:  
```JavaScript
const onResetPage = useCallback(
    () => dispatch({ type: 'reset', initialState: props }),
    [props.items.length]
  )
```
but somehow it doesn't work, will try to reproduce it somewhere

@edit Something like this: https://codesandbox.io/s/vv5q4jx180

**Comment by drixie** [comment]
@dylangarcia This issue still exists. 

Thanks for a very simple solution!

Also, is it possible to have a method that lists out page numbers in a specified format?
